### ISSUE TITLE
AttributeError: 'Armature' object has no attribute 'display_type'

### ISSUE THREAD

**Issue by Eloque** [makehumancommunity/makehuman-plugin-for-blender#41]
This happens when importing a human in Blender 2.79b. There are indeed no bones available in the the model after the import.

Seems to work fine in 2.8 as far as I can tell.

```
>> bpy.ops.mh_community.import_body()
Import body
GROUND MEAN: -1.0187471151351928
WARNING: face index 18486 > 18486
Resuing existing material body
Error: Traceback (most recent call last):
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\operators\bodyimport.py", line 14, in execute
    ImportBodyBinary()
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 89, in __init__
    FetchServerData('getBodyMeshInfo', self.gotBodyInfo)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 14, in callback
    self.readyFunction(... truncated
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\operators\bodyimport.py", line 14, in execute
    ImportBodyBinary()
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 89, in __init__
    FetchServerData('getBodyMeshInfo', self.gotBodyInfo)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 127, in gotBodyInfo
    FetchServerData('getBodyVerticesBinary',self.gotVerticesData,True)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 160, in gotVerticesData
    FetchServerData('getBodyFacesBinary',self.gotFacesData,True)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 189, in gotFacesData
    FetchServerData('getBodyTextureCoordsBinary', self.gotTextureCoords, True)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 207, in gotTextureCoords
    FetchServerData('getBodyFaceUVMappingsBinary', self.gotFaceUVMappings, True)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 241, in gotFaceUVMappings
    self.afterMeshData()
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 383, in afterMeshData
    FetchServerData('getBodyMaterialInfo',self.gotBodyMaterialInfo)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 400, in gotBodyMaterialInfo
    FetchServerData('getSkeleton', self.gotSkeleton)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "C:\Users\Eloque\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\mh_sync\import_body_binary.py", line 449, in gotSkeleton
    self.armatureObject.data.display_type = 'WIRE'
AttributeError: 'Armature' object has no attribute 'display_type'

location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:189

```

**Comment by Aranuvir** [comment]
That's the problem of supporting different Blender APIs. I simply forgot to test it on 2.79...
Should be fixed, now.
Closing, though it can be reopened if there is something else, I had forgotten :)
